CREATE TABLE orders (
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT NOT NULL,
  status VARCHAR(20) NOT NULL,
  total INT NOT NULL DEFAULT 0,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  INDEX (user_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT
);

CREATE TABLE order_items (
  id INT PRIMARY KEY AUTO_INCREMENT,
  order_id INT NOT NULL,
  sku_id VARCHAR(80) NOT NULL,
  product_id VARCHAR(64) NOT NULL,
  sku_ref_id BIGINT UNSIGNED NULL,
  product_ref_id BIGINT UNSIGNED NULL,
  name VARCHAR(191) NOT NULL,
  size VARCHAR(16) NOT NULL,
  unit_price INT NOT NULL DEFAULT 0,
  qty INT NOT NULL DEFAULT 0,
  INDEX (order_id),
  INDEX (sku_ref_id),
  INDEX (product_ref_id),
  FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
  FOREIGN KEY (sku_ref_id) REFERENCES skus(id) ON DELETE SET NULL,
  FOREIGN KEY (product_ref_id) REFERENCES products(id) ON DELETE SET NULL
);
